import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'es', 'fr', 'tl', 'zh_Hans', 'zh_Hant', 'ru'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? frText = '',
    String? tlText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? ruText = '',
  }) =>
      [
        enText,
        esText,
        frText,
        tlText,
        zh_HansText,
        zh_HantText,
        ruText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Login
  {
    '6zhemcqt': {
      'en': 'Sign Up',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tlf7yiuz': {
      'en': 'Welcome,\nSign up below to start budgeting like a Pro!',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iawuw28l': {
      'en': 'Email Address',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gakmsl2l': {
      'en': 'First Name',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'df5wa8q3': {
      'en': 'Last Name',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ctiju6eq': {
      'en': 'New Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'pwbg6n4g': {
      'en': 'Confirm Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bwxngpq0': {
      'en': 'May we contact you?',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'h0ovelqk': {
      'en': 'Opt-In to pigs and marketing in your inbox!',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ble29zwu': {
      'en': 'Sign Up',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'auk30bb4': {
      'en': 'Accept Invite',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'k4qxkjcy': {
      'en': 'Terms',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '88nldcqd': {
      'en': 'Privacy',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j424s7ln': {
      'en': 'Legal',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aiqn1km5': {
      'en': 'Disclaimer: The Purple Piggy Bank LLC Is Not A Bank',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm1x0c8eo': {
      'en': 'Sign In',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wap3zbs6': {
      'en': 'Welcome Back! \nSign In below to get started',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6nskejwt': {
      'en': 'Email Address',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ms6j5kyn': {
      'en': 'Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ca8eqzrn': {
      'en': 'Sign In',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm4o2is6k': {
      'en': 'Forgot Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ffli1euo': {
      'en': 'Accept Invite',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vop441t3': {
      'en': 'Terms',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm0gm5avj': {
      'en': 'Privacy',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'c0yvqsyg': {
      'en': 'Legal',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lpr4l9ey': {
      'en': 'Disclaimer: The Purple Piggy Bank LLC Is Not A Bank',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7v1ncahg': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Ledger
  {
    'ne1dsipt': {
      'en': 'Ledger',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ne8su8g7': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kzy90lg1': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y1wzq8cs': {
      'en': 'Budget',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u6b4mzwm': {
      'en': 'Turn off All filters to view EVERYTHING',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'x8j8s3es': {
      'en': 'This Month Up to Today',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'klbtbbz5': {
      'en': 'Default View',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'q3a4pp5v': {
      'en': 'View This Full Month',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wzsinpdm': {
      'en': 'All Transactions for the current Month',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nokqubxu': {
      'en': 'Cleared Transactions',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5sdir9z5': {
      'en': 'All Cleared Transactions regardless of date',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ylfa4x4e': {
      'en': '1',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '717nxosy': {
      'en': '2',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9ys2bg0c': {
      'en': '3',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'q7u3yx15': {
      'en': '4',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '312koiqm': {
      'en': '5',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'heuud5al': {
      'en': '6',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aldggef3': {
      'en': '7',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'chckzjum': {
      'en': '8',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vw7nvkt5': {
      'en': '9',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'demcvpmc': {
      'en': '10',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j2yc0093': {
      'en': '11',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tkpfv5ee': {
      'en': '12',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '54i3hwnu': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ollann0r': {
      'en': 'Month',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w5gfg0q4': {
      'en': '2024',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'mamil3vk': {
      'en': '2025',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ov0g1r1n': {
      'en': '2026',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vo0ubcaf': {
      'en': '2027',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kg4pfflz': {
      'en': '2028',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lvdkfj8s': {
      'en': '2029',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cassuvj1': {
      'en': '2030',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jug681q1': {
      'en': '2031',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7qmj78v4': {
      'en': '2032',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iooc9hfu': {
      'en': '2033',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eg4el8cm': {
      'en': '2034',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bpeqqh86': {
      'en': '2035',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ewmumqy3': {
      'en': '2036',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gwaw8cnv': {
      'en': '2037',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5a2h9i8i': {
      'en': '2038',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '31mipnvq': {
      'en': '2039',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f3ijny2j': {
      'en': '2040',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '61bgykag': {
      'en': '2041',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xb8yxmxs': {
      'en': '2042',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7dr08m94': {
      'en': '2043',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0c66uvb4': {
      'en': '2044',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'voa83xlp': {
      'en': '2045',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oux6z30c': {
      'en': '2046',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'p5cpofum': {
      'en': '2047',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ntlw8kvl': {
      'en': '2048',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5kluln6y': {
      'en': '2049',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'pngmkocw': {
      'en': '2050',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'n019bx8h': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'sh51edbc': {
      'en': 'Year',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2qm5vjd7': {
      'en': 'Threshold',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '73lkrwlj': {
      'en': 'Ledger',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Bills
  {
    'jfqc2np8': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hh3ovkmw': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wy0g1tkg': {
      'en': 'Budget',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5i6gmt1b': {
      'en': 'View or Edit All Bills',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'biwtfox2': {
      'en': 'Due',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '094bqeon': {
      'en': 'Due Today',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'syw5zyzo': {
      'en': 'Past Due',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4igamubx': {
      'en': 'Paid',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'grs45l31': {
      'en': 'Paid',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ktydx6q3': {
      'en': 'Future',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0mfyf67c': {
      'en': 'Not Due Yet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b9xmdza3': {
      'en': 'Bills',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zuxkjjxf': {
      'en': 'Bills',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Incomes
  {
    '40jyp3sn': {
      'en': 'Incomes',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '161heoda': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'i5q8cd58': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b2ukmat3': {
      'en': 'Budget',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iyh5lfzl': {
      'en': 'Your Incomes',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fmryx8tt': {
      'en': 'Below is a list of your Incomes for the month',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's50xnyoi': {
      'en': 'Total ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u2j7ir17': {
      'en': 'Next Payday ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jm9ucla1': {
      'en': 'Income',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Options
  {
    'egkillaa': {
      'en': 'Options',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uyusg8mi': {
      'en': 'Account',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '980eluqn': {
      'en': 'Add Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kpyszh1w': {
      'en': 'Edit Household Name',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bpwa2rc2': {
      'en': 'Invitations',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5ybi6gjg': {
      'en': 'Edit Members',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4mbx7eoq': {
      'en': 'Notifications',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'apfug1th': {
      'en': 'Export to File',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3gtfjkc7': {
      'en': 'DEBUG',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yw3eh4o1': {
      'en': 'Light Mode',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'elhpyvgh': {
      'en': 'Dark Mode',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'go4wy83u': {
      'en': 'Export to File',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6mrnu68q': {
      'en': 'Options',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // SalesPage
  {
    'qqz4s1wh': {
      'en': 'Silly Name, Serious Budgeting',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ide3jysl': {
      'en': 'Share and Collaborate on your Budget',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's1tjrz0e': {
      'en': 'Export Reports to CSV and QBB',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fez1nrmg': {
      'en': 'Easily keep your ledger up to date',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f1few2ma': {
      'en': 'Never miss a bill, Get bill reminders!',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dk1yaqrh': {
      'en': 'Bill Password Manager',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ydkwt9n6': {
      'en': 'Create Unlimited Number Of Budgets',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cffzoh25': {
      'en': 'Monthly',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'htpc9bto': {
      'en': 'Full Access \$2.99/Month',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w05zpioh': {
      'en': 'Annual',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j69lzulh': {
      'en': 'Full Access \$29.99/Year - 2 Months Free',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cjbpl603': {
      'en': 'Forever',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bphr994u': {
      'en': 'Full Access \$149.99 - Forever',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'c6yc0uex': {
      'en': 'Continue',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jydlwx7d': {
      'en': 'Legal',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nyyhtd6x': {
      'en': 'Terms',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1qo0zdkn': {
      'en': 'Privacy',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iw5r0ouh': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // AddBill
  {
    'xolfnmsg': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u68jwc56': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ayjha8wg': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wz8xfd21': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '93bb28l6': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eq43j8q3': {
      'en': 'Wallet*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'z38e58us': {
      'en': '1st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aq2igkb8': {
      'en': '2nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bftwh0an': {
      'en': '3rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7oc5se4q': {
      'en': '4th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j2c8k382': {
      'en': '5th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kwjcjtme': {
      'en': '6th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b1mn49f0': {
      'en': '7th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xeznoqgp': {
      'en': '8th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jbli9qzy': {
      'en': '9th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uigabna1': {
      'en': '10th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yyj1k0o9': {
      'en': '11th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'c5ko5efe': {
      'en': '12th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fsveyah1': {
      'en': '13th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tv0s7f03': {
      'en': '14th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8tk9f4dt': {
      'en': '15th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1p2mv3tm': {
      'en': '16th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3nds0ked': {
      'en': '17th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '055s0jud': {
      'en': '18th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'znirg8qp': {
      'en': '19th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0h4wbjxg': {
      'en': '20th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oevb4cs5': {
      'en': '21st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eoc5r5h1': {
      'en': '22nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lkg0iyhf': {
      'en': '23rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'l9420ap5': {
      'en': '24th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jeuq995m': {
      'en': '25th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vt5uu9xc': {
      'en': '26th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'auqg71xr': {
      'en': '27th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ez9te7pd': {
      'en': '28th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hl9orti3': {
      'en': '29th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2uzp9ue6': {
      'en': '30th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yqvchhdk': {
      'en': '31st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7cchiavh': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7yyqr2n7': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j27n5zwn': {
      'en': 'Day Of the Month*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8jzranyj': {
      'en': 'One time',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aahmo7d6': {
      'en': 'Weekly ( 7 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xijr6her': {
      'en': 'Bi-Weekly ( 14 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j0a5hpyz': {
      'en': 'Monthly ( 30 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '63fezisq': {
      'en': 'Bi-Monthly ( 60 Days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bqw13efk': {
      'en': 'Quarterly ( 90 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ny6rz7w2': {
      'en': 'Semi-Annually ( 180 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xg1kmor2': {
      'en': 'Annually ( Yearly)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4sbhskwe': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w8epsu83': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wb35eigh': {
      'en': 'Frequency*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dkqxjcoz': {
      'en': 'Bill Name*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ox42fq89': {
      'en': 'Amount*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b6usar2t': {
      'en': 'Category*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gtr8cwi8': {
      'en': 'Description*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kodugv68': {
      'en': 'Biller URL',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '75cbsolj': {
      'en': 'Biller Username',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1u8tsyo2': {
      'en': 'Biller Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6lqf7m2e': {
      'en': 'Shared with household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j2u7wng5': {
      'en': 'Continue',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oanero6t': {
      'en': 'Add Bill',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qgshmkwx': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // BillDetails
  {
    'i4mekdfq': {
      'en': 'Bill Details',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xrlz2qzb': {
      'en': 'Modify the Bill if you like and click Edit Bill',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8e59avrn': {
      'en': '1st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'h7buo1qh': {
      'en': '2nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '36lklqss': {
      'en': '3rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fr7hkbb5': {
      'en': '4th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fozt5e66': {
      'en': '5th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1k8tbkep': {
      'en': '6th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iwsgxpls': {
      'en': '7th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yh8iwhzw': {
      'en': '8th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'exxpad0z': {
      'en': '9th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jcyys65u': {
      'en': '10th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'z3kh4q0h': {
      'en': '11th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3bk9sv0f': {
      'en': '12th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3sn8lw3d': {
      'en': '13th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6lcqhoqx': {
      'en': '14th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ghwj4cdv': {
      'en': '15th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tgstk6p4': {
      'en': '16th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vyi580fy': {
      'en': '17th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nh6v7tj7': {
      'en': '18th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kst2e9h7': {
      'en': '19th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tzvalqct': {
      'en': '20th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hqvj0xs6': {
      'en': '21st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '36jfu1te': {
      'en': '22nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gpjhj5l1': {
      'en': '23rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gmlxiwf7': {
      'en': '24th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'k0331g1o': {
      'en': '25th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4kye0fir': {
      'en': '26th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'x38jeewd': {
      'en': '27th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ekskhfwj': {
      'en': '28th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'a2vjkm84': {
      'en': '29th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '22z8x3t1': {
      'en': '30th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'otfgkkwo': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ckzg4mwp': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'upkxqd9z': {
      'en': 'Day Of The Month (initially Due)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hvii6tqc': {
      'en': '1st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zskavxo7': {
      'en': '2nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'luvpvckf': {
      'en': '3rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9oy1jopx': {
      'en': '4th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '30a9tc9q': {
      'en': '5th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oi3xzdiv': {
      'en': '6th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ar30wi5o': {
      'en': '7th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b65lyv5e': {
      'en': '8th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8vfmh388': {
      'en': '9th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wgdkkakh': {
      'en': '10th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zg9bmsvj': {
      'en': '11th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ifi9o59r': {
      'en': '12th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lg72uxhx': {
      'en': '13th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lrx3dzmc': {
      'en': '14th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iicoqy61': {
      'en': '15th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9ca7e1x4': {
      'en': '16th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'e3fpzcha': {
      'en': '17th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'r02ptsmz': {
      'en': '18th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6v5vjiv0': {
      'en': '19th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's4yju1o0': {
      'en': '20th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tbg6bbr0': {
      'en': '21st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '609opnzi': {
      'en': '22nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xwmfgdfq': {
      'en': '23rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f7qa87pa': {
      'en': '24th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xbp2ne2k': {
      'en': '25th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2qzh4ecc': {
      'en': '26th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7q9wdryh': {
      'en': '27th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5pd59shx': {
      'en': '28th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'suojswad': {
      'en': '29th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cebc3dix': {
      'en': '30th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f78pt67o': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dt6hnwkl': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ealks1um': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'axa55th6': {
      'en': '1st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7lw6s9ar': {
      'en': '2nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'q3sph9pk': {
      'en': '3rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xwtd5e11': {
      'en': '4th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wzyctyxe': {
      'en': '5th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ix2r46mv': {
      'en': '6th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5qvc51x7': {
      'en': '7th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ohdowltj': {
      'en': '8th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ejawf92x': {
      'en': '9th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'o2r2k0kt': {
      'en': '10th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8nu6vvb7': {
      'en': '11th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1n5mglj6': {
      'en': '12th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1jvfgd8v': {
      'en': '13th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'l14cdz3i': {
      'en': '14th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'agof75dc': {
      'en': '15th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bdehezfu': {
      'en': '16th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uzrj3wzo': {
      'en': '17th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vyhn7sso': {
      'en': '18th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's1rdrfgd': {
      'en': '19th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oj3bjy7v': {
      'en': '20th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dzejkvsg': {
      'en': '21st',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'sd28p2ol': {
      'en': '22nd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'akxdqg8d': {
      'en': '23rd',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'c2y148pg': {
      'en': '24th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'k13dd4sb': {
      'en': '25th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'btno9nh5': {
      'en': '26th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ltr2nfwv': {
      'en': '27th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7n5ytw6u': {
      'en': '28th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'otjohq69': {
      'en': '29th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0lvh2n8a': {
      'en': '30th',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'l0sqhh74': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kpynn7fn': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ovqxv27p': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uvxopr0k': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'o0gcll4n': {
      'en': 'Bill Name',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hxcg4uyb': {
      'en': 'Amount',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iy2p2xjl': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cb7hynio': {
      'en': 'Once',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5dlg1uxu': {
      'en': 'Weekly (7 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xgfklnwm': {
      'en': 'Biweekly (14 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lvu96m2n': {
      'en': 'Monthly (30 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'foahaxvi': {
      'en': 'Bimonthly (60 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ulek7uon': {
      'en': 'Quarterly (90 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'r5fy1h0j': {
      'en': 'Semi-Annually (180 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u8me2d7f': {
      'en': 'Annually (yearly)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eebdojk3': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bqsh0w5f': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xqhzxlw9': {
      'en': 'Biller URL',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bknep6hr': {
      'en': 'Username',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'chz2x4t3': {
      'en': 'Password (shared with household)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'njk36nhn': {
      'en': 'Edit bill',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ccu8q20u': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // AddInvite
  {
    'tsdeukyk': {
      'en': 'Option 1',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tmxypnrl': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nooojqtw': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'e2fw52ov': {
      'en': 'Household*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'sdxhvlj8': {
      'en': 'Email Address*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ptr689xg': {
      'en': 'Who would you like to invite?',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '669ir6ox': {
      'en': 'Continue',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tk03ac4m': {
      'en': 'Add Invite',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ltleq4ez': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // CreateHousehold
  {
    's24dsttr': {
      'en': 'Household Name*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd3dvzzn7': {
      'en': 'Create Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4n9bfuc4': {
      'en': 'Add Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5fmcrkg2': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // EditHousehold
  {
    '9o2vdmcg': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'r17sd9lo': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hlsx90n9': {
      'en': 'Budget',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9gr2n8ox': {
      'en': 'New Household Name',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6exdehmp': {
      'en': 'Delete Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tyv5vxz1': {
      'en': 'Edit Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3zg2i8qg': {
      'en': 'Edit Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wg1wpbbv': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // EditMembers
  {
    '1irovwwp': {
      'en': 'Edit Members',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'h8qlfw02': {
      'en': 'Option 1',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oehhrdwn': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'g01000oc': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aapiu2i1': {
      'en': 'Household*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ne8td4r8': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // AddIncome
  {
    '5jnvbxz0': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6yjrydeb': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dzql5j46': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cpoz7c2p': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gynzpz72': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qo9cjmw7': {
      'en': 'Wallet*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yjhg3wz9': {
      'en': 'One time',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aar4qorx': {
      'en': 'Weekly ( 7 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '11zlj5g7': {
      'en': 'Bi-Weekly ( 14 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'r7v9fk2x': {
      'en': 'Monthly ( 30 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0n09yrj3': {
      'en': 'Bi-Monthly ( 60 Days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kgqri3bg': {
      'en': 'Quarterly ( 90 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3cfnt8qr': {
      'en': 'Semi-Annually ( 180 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1h1vu78a': {
      'en': 'Annually ( Yearly)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6gm5z1uv': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4j87ma53': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'pyyedr6m': {
      'en': 'Frequency*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b8li0iy9': {
      'en': 'Income Name*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'luob3wng': {
      'en': 'Amount*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v2yessnk': {
      'en': 'Continue',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uk65w8ul': {
      'en': 'Add Income',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'sfm478t1': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // EditIncome
  {
    'fm7nojwq': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4d4h4i7r': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kabgc36k': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aj2m79ln': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'q8supw4r': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bdfuhtda': {
      'en': 'Wallet*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '80ik4fx7': {
      'en': 'First Pay Day* (See Information)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'arvwtrwc': {
      'en': 'One time',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nld7onks': {
      'en': 'Weekly ( 7 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8em66ylg': {
      'en': 'Bi-Weekly ( 14 days)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1yoop7xn': {
      'en': 'Monthly ( 30 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm8k294mh': {
      'en': 'Bi-Monthly ( 60 Days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gbciroxq': {
      'en': 'Quarterly ( 90 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qtm4296c': {
      'en': 'Semi-Annually ( 180 days )',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tlx4vnzu': {
      'en': 'Annually ( Yearly)',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ql9ovfcy': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'a0q7sqa8': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lbb82mb2': {
      'en': 'Frequency*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ffswsw3a': {
      'en': 'Income Name*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1voq7lj0': {
      'en': 'Amount*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'pfkvfy9b': {
      'en': 'Edit Income',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2g6tphlk': {
      'en': 'Edit Income',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vdnajijt': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // AddTransaction
  {
    'edmtzvd8': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hv5g0gyv': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dmhivq7s': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oeiciiyx': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lnkxne88': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '72fnrx0t': {
      'en': 'Wallet*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ojwvwdeo': {
      'en': 'Add',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ezmac1xn': {
      'en': 'Subtract',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8wdetsrm': {
      'en': 'Type',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '607z8xgr': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4577feh4': {
      'en': 'Add or Subtract*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'st2ao9ro': {
      'en': 'Amount*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zphsworx': {
      'en': 'Description*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f255iycc': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nvvtkcz5': {
      'en': 'Tags',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rio16ero': {
      'en': 'Comma Separated list',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7sxrh96v': {
      'en': 'Cleared?',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'sct8eowz': {
      'en': 'True or False',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oe5w1lwd': {
      'en': 'Upload Receipt',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ki0vetmr': {
      'en': 'Continue',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aqme8uhg': {
      'en': 'Add Transaction',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ldkiqk84': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Categories
  {
    'zx72jrw9': {
      'en': 'Month To Date',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '17hwnciw': {
      'en': 'Year To Date',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wv68mjj6': {
      'en': 'Categories',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'atwceuhc': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // EditTransaction
  {
    '0grn4d40': {
      'en': 'Edit Transaction',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gc94e1yb': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // SearchTransactions
  {
    'r4m80m5d': {
      'en': 'Search',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ar603yxk': {
      'en': 'Search  Keywords, Amounts, Tags, Categories...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7tvb5lfk': {
      'en': 'Search Transactions',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'laaylt41': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // TransactionDetails
  {
    'nvyg6dlc': {
      'en': 'Description: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yx3y9wxn': {
      'en': 'Amount: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kdijiniz': {
      'en': 'Date: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zv2jqgi3': {
      'en': 'Category: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zx9vdqbz': {
      'en': 'Created At: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dry9pbcy': {
      'en': 'Updated At:  ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u0s67mcn': {
      'en': 'Running Total: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xcluxzwh': {
      'en': 'Tags: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aafc6vie': {
      'en': 'Household Name: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '67r3wu2q': {
      'en': 'Wallet Name',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'spqxdlzo': {
      'en': 'Wallet Type',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3fgw941d': {
      'en': 'Wallet Description',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ok223iba': {
      'en': 'Type',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bm1nz2z4': {
      'en': 'Status:',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'p1bjs3as': {
      'en': 'Toggle me',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5yq85eeh': {
      'en': 'Day Of The Month Due (initially): ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uy72d85h': {
      'en': 'URL: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rvd246zf': {
      'en': 'Username: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w99uv5kg': {
      'en': 'Password: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gix7vahj': {
      'en': 'Frequency: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7wg6fiyx': {
      'en': 'First Payday: ',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vb34m355': {
      'en': 'Attachment',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rjn9dg1u': {
      'en': 'Transaction',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ln2bbsmm': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // EditNotification
  {
    'r0ki56im': {
      'en': 'Pick a New Date',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'djbaasoz': {
      'en': 'Title*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0k227e8q': {
      'en': 'Message',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rrgtpl2r': {
      'en': 'Frequency',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vqxl1f8p': {
      'en': 'Day Of Month',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dw0qog5m': {
      'en': 'Continue',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'sjbxjp5t': {
      'en': 'Edit Notification',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zt0xqt7o': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Notifications
  {
    'gs41b1cl': {
      'en': 'Notifications',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'mxnq9p6w': {
      'en': 'Notifications',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Wallets
  {
    'fow3t0no': {
      'en': 'example',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uo4dz4vi': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gf3ojsxr': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'retso69b': {
      'en': 'Select Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uyej0lms': {
      'en': 'Wallets',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nawp5pzi': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // EditWallet
  {
    'hznetjxv': {
      'en': 'Edit Wallet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w14dp5s3': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // WalletDetails
  {
    '7hqdz2sf': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yx5h31yy': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Export
  {
    'qp8xayzu': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vznipi0b': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'crtljgzn': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1egmgrki': {
      'en': 'Export Ledger To CSV File',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'k46xyx3b': {
      'en': 'Export Ledger To QBO File',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lvqlmgy2': {
      'en': 'Export Search',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ms5y0v62': {
      'en': 'Export',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5vna6h54': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // ExportSearch
  {
    'o9803fio': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5d8af0fi': {
      'en': 'Year End',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fzp96s5h': {
      'en': 'Tracking',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'i3zd6f9h': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '530wbaxg': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xay6x19c': {
      'en': 'Report Type',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tx8xi7h1': {
      'en': 'Export To CSV',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aaci8h3r': {
      'en': 'Export Search',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3re730rk': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // ExportToCSV
  {
    '4tc5vh54': {
      'en': 'Option 1',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7wmh4mor': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '25a3lztl': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1pzc7gh3': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ww7mb9a9': {
      'en': 'Export To CSV',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vvwpevj5': {
      'en': 'Export To CSV',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1qlq1sxk': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // ExportToQBO
  {
    '7r48oumm': {
      'en': 'Option 1',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7wfjl7kk': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cxnv51tj': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zvzy2gib': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm5km0x1r': {
      'en': 'Export To QBB/QBO',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vxc0c5my': {
      'en': 'Export To QBO',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wmcwvxd8': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // forgotPassword
  {
    'e55bo3lf': {
      'en': 'Email Address*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ayq1foub': {
      'en': 'Please Provide....',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6sf2qx9i': {
      'en': 'Continue',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'o65jqyvw': {
      'en': 'Forgot Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gnngyrri': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // updateUser
  {
    'iq05qu7h': {
      'en': 'Update User',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's4m03vug': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // DeleteUser
  {
    'w4ctass4': {
      'en': 'Delete Account',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0mj2z80r': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // AcceptInvite
  {
    '4cpg0ofw': {
      'en': 'Accept Invite',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'p51z1k3z': {
      'en': 'Welcome,\nSign up below to start budgeting like a Pro!',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rymctou4': {
      'en': 'Invitation Code*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2qggjd52': {
      'en': 'Email Address*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vfxskcqs': {
      'en': 'First Name*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5zz7j2ff': {
      'en': 'Last Name*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '941sjrtl': {
      'en': 'New Password*',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ce6lg65e': {
      'en': 'Confirm Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0cj917mj': {
      'en': 'May we contact you?',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jm93kmdk': {
      'en': 'Opt-In to pigs and marketing in your inbox!',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cj1c4p6g': {
      'en': 'Sign Up',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zd7kkpht': {
      'en': 'Terms',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zpnohlc5': {
      'en': 'Privacy',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lqx58nhi': {
      'en': 'Legal',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'q0ga7s09': {
      'en': 'Disclaimer: The Purple Piggy Bank LLC Is Not A Bank',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7btvsdck': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // ChangePassword
  {
    '9s90gdsx': {
      'en': 'Change Password',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b0qkk85v': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // ViewAllBills
  {
    'jo1bk6zp': {
      'en': 'All Bills',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qe8s722x': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // EditLEdgerEntry
  {
    'dm5i7e9o': {
      'en': 'Edit Ledger Entry',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1wnxa45e': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // AddWallet
  {
    'mktnom6s': {
      'en': 'Add Wallet',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hvn04fcj': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Account
  {
    'tl8c3ips': {
      'en': 'Billing Portal',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'mrkywghp': {
      'en': 'Profile',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gmy6s7c7': {
      'en': 'Edit Household Members',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'n7o598t7': {
      'en': 'Purchase or Redeem',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8fxcf5er': {
      'en': 'Account Details',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6c3wp5t0': {
      'en': 'More',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Miscellaneous
  {
    '0vgxcamc': {
      'en':
          'In order to take a picture of a receipt, this app requires permissions for camera access',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'l2qb7t33': {
      'en':
          'In order to upload a picture of a receipt, this app requires permissions for photo library',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9xgeywo0': {
      'en':
          'In order to add a picture of a receipt from your photo library, this app requires permissions to your photo library.',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'clt9qi38': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ero1sm01': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'g7ntb2hh': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6upbbx5y': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'va57impl': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xxhu6go8': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4to612do': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6ko7tmcw': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kjw0xu08': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8ug73h94': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yp33rmps': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ccjyrpwd': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'sycgo71p': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '36ab0wbi': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'mrx29hyd': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rkxari8d': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jc1aoajd': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hp2k3ef9': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2psfuflt': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gw3uu1bb': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0n1z5jy9': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uwjt06wq': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qzmhfpp3': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rudz437g': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ti8mv0di': {
      'en': '',
      'es': '',
      'fr': '',
      'ru': '',
      'tl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
